---
title: "Scientific Output"
listing:
  contents: scientific_output.qmd
  sort: "date desc"
  type: default
  categories: false
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

# Publications

* Cseresznye, A., Hardy, E., Bamai, Y. A., Cleys, P., Poma, G., Malarvannan, G., Scheepers, P., Viegas, S., Martins, C., Porras, S. P., Santonen, T., Godderis, L., Verdonck, J., Poels, K., Silva, M. J., Louro, H., Mārtiņsone, I., Akūlova, L., Van Dael, M., . . . Covaci, A. (2024). HBM4EU E-waste study: Assessing persistent organic pollutants in blood, silicone wristbands, and settled dust among E-waste recycling workers in Europe. Environmental Research, 118537. [https://doi.org/10.1016/j.envres.2024.118537](https://doi.org/10.1016/j.envres.2024.118537)
* Cleys, P., Hardy, E., Bamai, Y. A., Poma, G., Cseresznye, A., Malarvannan, G., Scheepers, P., Viegas, S., Porras, S. P., Santonen, T., Godderis, L., Verdonck, J., Poels, K., Martins, C., Silva, M. J., Louro, H., Mārtiņsone, I., Akūlova, L., Van Nieuwenhuyse, A., . . . Covaci, A. (2024). HBM4EU e-waste study: Occupational exposure of electronic waste workers to phthalates and DINCH in Europe. International Journal of Hygiene and Environmental Health, 255, 114286. [https://doi.org/10.1016/j.ijheh.2023.114286](https://doi.org/10.1016/j.ijheh.2023.114286)
* Yin, S., McGrath, T. J., Cseresznye, A., Bombeke, J., Poma, G., & Covaci, A. (2023). Assessment of silicone wristbands for monitoring personal exposure to chlorinated paraffins (C8-36): A pilot study. Environmental Research, 224, 115526. [https://doi.org/10.1016/j.envres.2023.115526](https://doi.org/10.1016/j.envres.2023.115526)
* Huguenard, C., Cseresznye, A., Darcey, T., Nkiliza, A., Evans, J. E., Hazen, S. L., Mullan, M., Crawford, F., & Abdullah, L. (2023). Age and APOE affect L-carnitine system metabolites in the brain in the APOE-TR model. Frontiers in Aging Neuroscience, 14. [https://doi.org/10.3389/fnagi.2022.1059017](https://doi.org/10.3389/fnagi.2022.1059017)
* Huguenard, C., Cseresznye, A., Evans, J. E., Darcey, T., Nkiliza, A., Keegan, A. P., Luis, C. A., Bennett, D. A., Arvanitakis, Z., Yassine, H. N., Mullan, M., Crawford, F., & Abdullah, L. (2023). APOE ε4 and Alzheimer’s disease diagnosis associated differences in L-carnitine, GBB, TMAO, and acylcarnitines in blood and brain. Current Research in Translational Medicine, 71(1), 103362. [https://doi.org/10.1016/j.retram.2022.103362](https://doi.org/10.1016/j.retram.2022.103362)
* Nkiliza, A., Parks, M., Cseresznye, A., Oberlin, S., Evans, J. E., Darcey, T., Aenlle, K., Niedospial, D., Mullan, M., Crawford, F., Klimas, N. G., & Abdullah, L. (2021). Sex-specific plasma lipid profiles of ME/CFS patients and their association with pain, fatigue, and cognitive symptoms. Journal of Translational Medicine, 19(1). [https://doi.org/10.1186/s12967-021-03035-6](https://doi.org/10.1186/s12967-021-03035-6)
* Joshi, U., Evans, J. E., Pearson, A., Saltiel, N., Cseresznye, A., Darcey, T., Ojo, J., Keegan, A. P., Oberlin, S., Mouzon, B., Paris, D., Klimas, N. G., Sullivan, K., Mullan, M., Crawford, F., & Abdullah, L. (2020). Targeting sirtuin activity with nicotinamide riboside reduces neuroinflammation in a GWI mouse model. Neurotoxicology, 79, 84–94. [https://doi.org/10.1016/j.neuro.2020.04.006](https://doi.org/10.1016/j.neuro.2020.04.006)
* Huguenard, C., Cseresznye, A., Evans, J. E., Oberlin, S., Langlois, H., Ferguson, S., Darcey, T., Nkiliza, A., Dretsch, M. N., Mullan, M., Crawford, F., & Abdullah, L. (2020). Plasma Lipidomic Analyses in Cohorts With mTBI and/or PTSD Reveal Lipids Differentially Associated With Diagnosis and APOE ε4 Carrier Status. Frontiers in Physiology, 11. [https://doi.org/10.3389/fphys.2020.00012](https://doi.org/10.3389/fphys.2020.00012)
* Joshi, U., Pearson, A., Evans, J. E., Langlois, H., Saltiel, N., Ojo, J., Klimas, N. G., Sullivan, K., Keegan, A. P., Oberlin, S., Darcey, T., Cseresznye, A., Raya, B., Paris, D., Hammock, B. D., Vasylieva, N., Hongsibsong, S., Stern, L. J., Crawford, F., . . . Abdullah, L. (2019). A permethrin metabolite is associated with adaptive immune responses in Gulf War Illness. Brain Behavior and Immunity, 81, 545–559. [https://doi.org/10.1016/j.bbi.2019.07.015](https://doi.org/10.1016/j.bbi.2019.07.015)
* Wang, M., Palavicini, J. P., Cseresznye, A., & Han, X. (2017). Strategy for Quantitative Analysis of Isomeric Bis(monoacylglycero)phosphate and Phosphatidylglycerol Species by Shotgun Lipidomics after One-Step Methylation. Analytical Chemistry, 89(16), 8490–8495. [https://doi.org/10.1021/acs.analchem.7b02058](https://doi.org/10.1021/acs.analchem.7b02058)


# Conference talks

* **Adam Cseresznye**, Fatima den Ouden, Liesa Engelen, Elias Maris, Giulia Poma, Roger Peró Gascón, Arnau Vich Vila, Muriel Derrien, Lieselot Y Hemeryck, Ellen De Paepe, Marthe De Boevre, Jeroen Raes, Sarah De Saeger, Tim S Nawrot, Lynn Vanhaecke, Adrian Covaci. Persistent organic pollutants in cord plasma in a Flemish birth cohort. Dioxin, Singapore, 2024.  
* **Adam Cseresznye**, Fatima den Ouden, Liesa Engelen, Jasper Bombeke, Giulia Poma, Thomas J McGrath, Roger Peró Gascon, Gwen Falony, Ellen De Paepe, Lieselot Y Hemeryck, Tim S Nawrot, Jeroen Raes, Lynn Vanhaecke, Sarah De Saeger, Marthe De Boevre, Adrian Covaci. Serum Levels of Persistent Organic Pollutants in the Flemish Gut Flora Project Cohort. Dioxin, Maastricht, the Netherlands, 2023.  
* **Emilie M. Hardy**, Adam Cseresznye , Paul T.J. Scheepers, Maria Torres Toda, Yu Ait Bamai, Simo Porras , Susana Viegas, Tiina Santonen, Adrian Covaci, An van Nieuwenhuyse, Radu C. Duca and HBM4EU e-waste study team. Assessment of e-waste occupational exposure to PCBs and PBDEs using settled dust and silicone wristbands analysis. Dioxin, Maastricht, the Netherlands, 2023.  
* **S. Yin**, T J. McGrath, A. Cseresznye, J. Bombeke, G. Poma, A. Covaci. Assessment of Silicone Wristbands for Monitoring Personal Exposure to Chlorinated
Paraffins (C8-36): a Pilot Study. Dioxin, Maastricht, the Netherlands, 2023.  
* **Paul T.J. Scheepers**, Susana Viegas, Radu-Corneliu Duca, Jelle Verdonck, Emilie Hardy, Adrian Covaci, Paulien Cleys, Adam Cseresznye, Thomas Goën, Karen S. Galea, Jelle Verdonck, Katrien Poels, Lode Godderis, Elizabeth Leese, Henriqueta Louro, Maria Silva, Sophie Ndaw, Simo Porras, Selma Mahiout, Tiina Santonen. The HBM4EU e-waste study: exploratory survey of worker’s exposure to toxic contaminants. ISES Annual Meeting, Chicago, IL, USA, 2023.  
* **Paulien Cleys**, Emilie Hardy, Yu Ait Bamai, Giulia Poma, Adam Cseresznye, Govindan Malarvannan, Paul T.J. Scheepers, Susana Viegas, Simo P. Porras, Tiina Santonen, Lode Godderis, Jelle Verdonck, Katrien Poels, Carla Martins, Maria João Silva, Henriqueta Louro, Inese Martinsone, Lāsma Akūlova, An van Nieuwenhuyse, Martien Graumans, Selma Mahiout, Radu Corneliu Duca, Adrian Covaci, HBM4EU e-waste study: Occupational Exposure of Electronic Waste Workers to Phthalates and Alternative Plasticizers in Europe. ISES Annual Meeting, Chicago, IL, USA, 2023.  
* **Adam Cseresznye**, P. Cleys, G. Poma, Y.A. Bamai, E. Hardy, P. Scheepers, S. Viegas, S. Porras, T. Santonen, R.C. Duca, A. Covaci, and HBM4EU E-Waste study group. HBM4EU E-waste study: persistent organic pollutants in e-waste recycling workers in the European Union. ISBM-12, Porto, Portugal, 2023. 


# Poster presentations

* R. Pero-Gascon, E. Maris, A. Cseresznye, F. den Ouden, L. Engelen, L.Y. Hemeryck, E. De Paepe, A. Vich Vila, S. Moossavi, M. Derrien, G. Poma, M. De Boevre, T.S. Nawrot, J. Raes, A. Covaci, L. Vanhaecke & S. De Saeger. FLEXiGUT: investigating the importance of the exposome in the development and progression of chronic low-grade gut inflammation. **Benelux Metabolomics Days, Utrecht, the Netherlands, 2023**
* Alicia Macan Schönleben , Thomas McGrath, Shanshan Yin, Adam Cseresznye, Alexander van Nuijs, *Giulia Poma*, Adrian Covaci. Chlorinated paraffins in seaweed chips – First insights using High-Resolution Mass Spectrometry. **Dioxin, Maastricht, the Netherlands, 2023**     
* Aurore Nkiliza, Claire Huguenard, Adam Cseresznye, Teresa Darcey, Corbin Bachmeier, James E. Evans, Andrew P. Keegan, Michael Mullan, Fiona Crawford and Laila Abdullah. The APOE e4 allele differentially influences plasma bioactive lipids in soldiers with mild TBI and PTSD, **AAIC, 2020**. 
* Huguenard C, Cseresznye A, Darcey T, Bachmeier C, Evans J E, Cheryl L, Keegan A. P, Mullan M,Crawford F, Abdullah L. APOE4-dependent and independent changes in acylcarnitines indicate lipid metabolic changes early on in Alzheimer’s disease. **AAIC, 2020**. 
* Cseresznye A, Huguenard C, Evans JE, Crawford F, Mullan M, Abdullah L. LC/MS/HRMS analysis of short to very long chain free fatty acids following charge reversal chemical derivatization [MP 364]. **ASMS conference, 2020**. 
*  Roderick G. Davies, Sarah Diane Oberlin, Adam Cseresznye, Laila Abdullah, Michael Mullan, Fiona Crawford, Megan C Schwarz, Marion Sourisseau, James E. Evans, Matthew J. Evans. Probing the Mechanism of Zika Infection/Replication Using Lipidomics And Proteomics Analyses [MP 364]. **ASMS conference, 2020**.
*  Cseresznye A, Huguenard C, Nkiliza A, Pearson A, Evans J, Crawford F, Mullan M, Abdullah L. Targeted analysis of microglia eicosanoid species by LC/MS/HRMS using high-resolution parallel- reaction monitoring. **Bioactive Lipid Conference, 2019**.
*  Nkiliza A, Huguenard C, Cseresznye A, Evans J, Raya B, Joshi U, Darcey T, Oberlin S, Crawford F, Mullan M, Abdullah L. Pharmacokinetic study of OEA for the treatment of Gulf war illness. **Bioactive Lipid Conference, 2019**.
* Evans J, Joshi U, Oberlin S, Cseresznye A, Oberlin S, Pearson A, Langlois H, Darcey T, Huguenard C, Davis R, Keegan A, Crawford F, Mullan M, Abdullah L. Nicotinamide riboside improves brain bioenergetics and reduces brain neuroinflammation in mouse model of Gulf war illness. **Bioactive Lipid Conference, 2019**.
* Huguenard C, Cseresznye A, Oberlin S, Langlois H, Darcey T, Dretsch M, Evans J, Crawford F, Mullan M, Abdullah L. Plasma lipidomic analysis in mild TBI and PTSD identify changes in ethanolamides, acylcarnitines and other circulating lipids. **Bioactive Lipid Conference, 2019**. 
* Huguenard C, Cseresznye A, Oberlin S, Langlois H, Darcey T, Dretsch M, Evans J, Crawford F, Mullan M, Abdullah L. Plasma lipidomics analyses for diagnostic classification of mild TBI and PTSD. **Keystone Conference, 2018**. 
* Abdullah L, Huguenard C, Cseresznye A, Evans J, Darcey T, Bachmeier C, Luis C, Crawford F, Mullan M. APOE4 and altered acylcarnitine profiles implicate mitochondria specific lipid metabolism dysfunction in preclinical Alzhemier’s disease. **Keystone Conference, 2018**. 
* Abdullah L, Huguenard C, Cseresznye A, Evans J, Darcey T, Bachmeier C, Luis C, Keegan A, Crawford F, Mullan M. APOE4 and altered carnitine, TMAO acylcarnitines implicate mitochondrial dysfunction in preclinical Alzhemier’s disease. **Keystone Conference, 2018**.

